DATA SEGMENT
 A DB 1,2,3,4,5,6,7,8,9,10
DATA ENDS
CODE SEGMENT
 ASSUME CS:CODE, DS:DATA
 START:
 MOV AX, DATA
 MOV DS, AX
 MOV CL, 10
 LEA SI, A ;use SI for storing the data
 MOV AH, 100
 MOV AL, 00
 L1:
 ADD AL, [SI] ;use square brackets to dereference SI
 INC SI
 DEC CL
 CMP CL, 00
 JNZ L1
 MOV AH, 4CH
 INT 21H
 CODE ENDS
END START
